# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wenexus-apps"
client_id = "97595bec3b075eb2936fbc714499bf66"
application_url = "https://earn-escape-oscar-cgi.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://earn-escape-oscar-cgi.trycloudflare.com/auth/callback",
  "https://earn-escape-oscar-cgi.trycloudflare.com/auth/shopify/callback",
  "https://earn-escape-oscar-cgi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "custom-app-functions.myshopify.com"
